services:
  frontend:
    build: ./
    ports:
      - "80:80"
    networks:
      - shacktopus-network
    restart: unless-stopped
    depends_on:
      - backend  # Ensure the backend is started before the frontend

  backend:
    build: ../reef/
    networks:
      - shacktopus-network
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb:27017/user_management?authSource=admin
    restart: unless-stopped
    depends_on:
      - mongodb  # Ensure MongoDB is started before the backend

  mongodb:
    image: mongo:8.0
    container_name: mongodb
    ports:
      - "27017:27017" # Expose port for debugging or external tools
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongodb_data:/data/db # Persistent storage for MongoDB
    networks:
      - shacktopus-network
    restart: unless-stopped

networks:
  shacktopus-network:
    driver: bridge

volumes:
  mongodb_data:
