services:
  frontend:
    build: ./
    ports:
      - "80:80"   # HTTP
      - "443:443" # HTTPS
    networks:
      - shacktopus-network
    depends_on:
      - backend  # Ensure the backend is started before the frontend

  backend:
    build: ../reef/
    # No need to expose ports here as communication works via docker network
    networks:
      - shacktopus-network
    environment:
      - NODE_ENV=production

networks:
  shacktopus-network:
    driver: bridge
